### ISSUE TITLE
OSError: ./LPC.dll: invalid ELF header

### ISSUE THREAD

**Issue by mohican521** [FACEGOOD/FACEGOOD-Audio2Face#88]
Traceback (most recent call last):
  File "step1_LPC.py", line 26, in <module>
    dll = cdll.LoadLibrary(os.path.join(project_dir, 'LPC.dll'))  # 加载 LPC.dll
  File "/opt/conda/envs/python3.7/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/opt/conda/envs/python3.7/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./LPC.dll: invalid ELF header

**Comment by diya-he** [comment]
dll文件是windows下的动态链接库，linux下应该不支持吧
